### ISSUE TITLE
Typos in README

### ISSUE THREAD

**Issue by wenjie2wang** [stc04003/pseudo-cure#1]
There are duplicated "with" in the README.  For instance,

> Fitting a mixture cure model **with with** the proposed pseudo-observation approach
> Fitting a bounded cumulative hazard model **with with** the proposed pseudo-observation approach

BTW, one other pitfall of `smcure` is reported in https://github.com/wenjie2wang/intsurv/issues/1.  Hopefully, it does not affect your analysis.

**Comment by stc04003** [comment]
Thanks! Fortunately, I don't think the pitfall of `smcure` affects our analysis.
